name: Deploy Chatbot Service to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Add SSH key for EC2 access
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.80.19.33 >> ~/.ssh/known_hosts

      # Step 3: Deploy code to EC2 instance
      - name: Deploy code to EC2
        run: |
          rsync -avz --exclude='node_modules' --exclude='.git' -e "ssh -i ~/.ssh/id_rsa" ./ ec2-user@54.80.19.33:/home/ec2-user/chatbot-ms/
          ssh -i ~/.ssh/id_rsa ec2-user@54.80.19.33 'cd /home/ec2-user/chatbot-ms && npm install && pm2 restart all'
